[package]
name = "zero2prod"
version = "0.1.0"
authors = ["Aleksandr Aibulatov <zap.aibulatov@gmail.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "zero2prod"
path = "src/main.rs"

[dependencies]
actix-web = "4"
reqwest = "0.12.7"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
