application:
  port: 8000
  hmac_secret: "4VsUXKQb9y3axdci85xnqHJaeNiuwlTJomNbXDe4oJ3ovqjtZSZIuva7HtGQtFqn"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: localhost
  sender_email: test@gmail.com
  authorization_token: "fake-tkn"
  timeout_milliseconds: 10000
redis_uri: "redis://localhost:6379"